-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-06-10 14:02:40 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE gabinet CASCADE CONSTRAINTS;

DROP TABLE gabinet_lekarski CASCADE CONSTRAINTS;

DROP TABLE miasto CASCADE CONSTRAINTS;

DROP TABLE pacjent CASCADE CONSTRAINTS;

DROP TABLE panstwo CASCADE CONSTRAINTS;

DROP TABLE pracownik CASCADE CONSTRAINTS;

DROP TABLE specjalizacja CASCADE CONSTRAINTS;

DROP TABLE sprzet CASCADE CONSTRAINTS;

DROP TABLE sprzet_w_gabinecie CASCADE CONSTRAINTS;

DROP TABLE typ_gabinetu CASCADE CONSTRAINTS;

DROP TABLE typ_oplaty CASCADE CONSTRAINTS;

DROP TABLE ulica CASCADE CONSTRAINTS;

DROP TABLE wizyta CASCADE CONSTRAINTS;

DROP TABLE wojewodztwo CASCADE CONSTRAINTS;

DROP TABLE wysokosc_zarobkow CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE gabinet (
    gabinet_id      NUMBER(2) NOT NULL,
    numer           NUMBER(3),
    typ_gabinetu_id NUMBER(2) NOT NULL
);

ALTER TABLE gabinet ADD CONSTRAINT gabinet_pk PRIMARY KEY ( gabinet_id );

CREATE TABLE gabinet_lekarski (
    gabinet_lekarski_id NUMBER(2) NOT NULL,
    nazwa               VARCHAR2(20),
    nr_domu             NUMBER(2),
    nr_mieszkania       NUMBER(2),
    telefon             CHAR(9),
    email               VARCHAR2(20),
    ulica_id            NUMBER(2) NOT NULL
);

ALTER TABLE gabinet_lekarski ADD CONSTRAINT gabinet_lekarski_pk PRIMARY KEY ( gabinet_lekarski_id );

CREATE TABLE miasto (
    miasto_id      NUMBER(2) NOT NULL,
    nazwa          VARCHAR2(20),
    wojewodztwo_id NUMBER(2) NOT NULL
);

ALTER TABLE miasto ADD CONSTRAINT miasto_pk PRIMARY KEY ( miasto_id );

CREATE TABLE pacjent (
    pacjent_id    NUMBER(2) NOT NULL,
    imie          VARCHAR2(20),
    nazwisko      VARCHAR2(30),
    nr_domu       NUMBER(2),
    nr_mieszkania NUMBER(2),
    telefon       CHAR(9),
    ulica_id      NUMBER(2) NOT NULL,
    pesel         CHAR(11)
);

ALTER TABLE pacjent ADD CONSTRAINT pacjent_pk PRIMARY KEY ( pacjent_id );

CREATE TABLE panstwo (
    panstwo_id NUMBER(2) NOT NULL,
    nazwa      VARCHAR2(20)
);

ALTER TABLE panstwo ADD CONSTRAINT panstwo_pk PRIMARY KEY ( panstwo_id );

CREATE TABLE pracownik (
    pracownik_id        NUMBER(2) NOT NULL,
    imie                VARCHAR2(20),
    nazwisko            VARCHAR2(30),
    nr_domu             NUMBER(2),
    nr_mieszkania       NUMBER(2),
    telefon             CHAR(9),
    ulica_id            NUMBER(2) NOT NULL,
    specjalizacja_id    NUMBER(2) NOT NULL,
    gabinet_lekarski_id NUMBER(2) NOT NULL
);

ALTER TABLE pracownik ADD CONSTRAINT pracownik_pk PRIMARY KEY ( pracownik_id );

CREATE TABLE specjalizacja (
    specjalizacja_id     NUMBER(2) NOT NULL,
    nazwa                VARCHAR2(30),
    wysokosc_zarobkow_id NUMBER(2) NOT NULL
);

ALTER TABLE specjalizacja ADD CONSTRAINT specjalizacja_pk PRIMARY KEY ( specjalizacja_id );

CREATE TABLE sprzet (
    sprzet_id NUMBER(2) NOT NULL,
    nazwa     VARCHAR2(30)
);

ALTER TABLE sprzet ADD CONSTRAINT sprzet_pk PRIMARY KEY ( sprzet_id );

CREATE TABLE sprzet_w_gabinecie (
    opis       VARCHAR2(30),
    sprzet_id  NUMBER(2) NOT NULL,
    gabinet_id NUMBER(2) NOT NULL
);

CREATE TABLE typ_gabinetu (
    typ_gabinetu_id NUMBER(2) NOT NULL,
    opis            VARCHAR2(30)
);

ALTER TABLE typ_gabinetu ADD CONSTRAINT typ_gabinetu_pk PRIMARY KEY ( typ_gabinetu_id );

CREATE TABLE typ_oplaty (
    typ_oplaty_id NUMBER(2) NOT NULL,
    opis          VARCHAR2(20),
    kwota         NUMBER(6, 2)
);

ALTER TABLE typ_oplaty ADD CONSTRAINT typ_oplaty_pk PRIMARY KEY ( typ_oplaty_id );

CREATE TABLE ulica (
    ulica_id  NUMBER(2) NOT NULL,
    nazwa     VARCHAR2(20),
    miasto_id NUMBER(2) NOT NULL
);

ALTER TABLE ulica ADD CONSTRAINT ulica_pk PRIMARY KEY ( ulica_id );

CREATE TABLE wizyta (
    wizyta_id     NUMBER(6) NOT NULL,
    data          DATE,
    godzina       INTERVAL DAY TO SECOND(0),
    pacjent_id    NUMBER(2) NOT NULL,
    pracownik_id  NUMBER(2) NOT NULL,
    gabinet_id    NUMBER(2) NOT NULL,
    typ_oplaty_id NUMBER(2) NOT NULL
);

ALTER TABLE wizyta ADD CONSTRAINT wizyta_pk PRIMARY KEY ( wizyta_id );

CREATE TABLE wojewodztwo (
    wojewodztwo_id NUMBER(2) NOT NULL,
    nazwa          VARCHAR2(20),
    panstwo_id     NUMBER(2) NOT NULL
);

ALTER TABLE wojewodztwo ADD CONSTRAINT wojewodztwo_pk PRIMARY KEY ( wojewodztwo_id );

CREATE TABLE wysokosc_zarobkow (
    wysokosc_zarobkow_id NUMBER(2) NOT NULL,
    kwota                NUMBER(7, 2)
);

ALTER TABLE wysokosc_zarobkow ADD CONSTRAINT wysokosc_zarobkow_pk PRIMARY KEY ( wysokosc_zarobkow_id );

ALTER TABLE gabinet_lekarski
    ADD CONSTRAINT gabinet_lekarski_ulica_fk FOREIGN KEY ( ulica_id )
        REFERENCES ulica ( ulica_id );

ALTER TABLE gabinet
    ADD CONSTRAINT gabinet_typ_gabinetu_fk FOREIGN KEY ( typ_gabinetu_id )
        REFERENCES typ_gabinetu ( typ_gabinetu_id );

ALTER TABLE miasto
    ADD CONSTRAINT miasto_wojewodztwo_fk FOREIGN KEY ( wojewodztwo_id )
        REFERENCES wojewodztwo ( wojewodztwo_id );

ALTER TABLE pacjent
    ADD CONSTRAINT pacjent_ulica_fk FOREIGN KEY ( ulica_id )
        REFERENCES ulica ( ulica_id );

ALTER TABLE pracownik
    ADD CONSTRAINT pracownik_gabinet_lekarski_fk FOREIGN KEY ( gabinet_lekarski_id )
        REFERENCES gabinet_lekarski ( gabinet_lekarski_id );

ALTER TABLE pracownik
    ADD CONSTRAINT pracownik_specjalizacja_fk FOREIGN KEY ( specjalizacja_id )
        REFERENCES specjalizacja ( specjalizacja_id );

ALTER TABLE pracownik
    ADD CONSTRAINT pracownik_ulica_fk FOREIGN KEY ( ulica_id )
        REFERENCES ulica ( ulica_id );

ALTER TABLE specjalizacja
    ADD CONSTRAINT specjalizacja_wysokosc_zar_fk FOREIGN KEY ( wysokosc_zarobkow_id )
        REFERENCES wysokosc_zarobkow ( wysokosc_zarobkow_id );

ALTER TABLE sprzet_w_gabinecie
    ADD CONSTRAINT sprzet_w_gabinecie_gabinet_fk FOREIGN KEY ( gabinet_id )
        REFERENCES gabinet ( gabinet_id );

ALTER TABLE sprzet_w_gabinecie
    ADD CONSTRAINT sprzet_w_gabinecie_sprzet_fk FOREIGN KEY ( sprzet_id )
        REFERENCES sprzet ( sprzet_id );

ALTER TABLE ulica
    ADD CONSTRAINT ulica_miasto_fk FOREIGN KEY ( miasto_id )
        REFERENCES miasto ( miasto_id );

ALTER TABLE wizyta
    ADD CONSTRAINT wizyta_gabinet_fk FOREIGN KEY ( gabinet_id )
        REFERENCES gabinet ( gabinet_id );

ALTER TABLE wizyta
    ADD CONSTRAINT wizyta_pacjent_fk FOREIGN KEY ( pacjent_id )
        REFERENCES pacjent ( pacjent_id );

ALTER TABLE wizyta
    ADD CONSTRAINT wizyta_pracownik_fk FOREIGN KEY ( pracownik_id )
        REFERENCES pracownik ( pracownik_id );

ALTER TABLE wizyta
    ADD CONSTRAINT wizyta_typ_oplaty_fk FOREIGN KEY ( typ_oplaty_id )
        REFERENCES typ_oplaty ( typ_oplaty_id );

ALTER TABLE wojewodztwo
    ADD CONSTRAINT wojewodztwo_panstwo_fk FOREIGN KEY ( panstwo_id )
        REFERENCES panstwo ( panstwo_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             0
-- ALTER TABLE                             30
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
