-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-06-12 10:42:59 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE gabinet_hurt CASCADE CONSTRAINTS;

DROP TABLE gabinet_lekarski_hurt CASCADE CONSTRAINTS;

DROP TABLE miasto_hurt CASCADE CONSTRAINTS;

DROP TABLE miesiac_hurt CASCADE CONSTRAINTS;

DROP TABLE pacjent_hurt CASCADE CONSTRAINTS;

DROP TABLE panstwo_hurt CASCADE CONSTRAINTS;

DROP TABLE pracownik_hurt CASCADE CONSTRAINTS;

DROP TABLE rok_hurt CASCADE CONSTRAINTS;

DROP TABLE specjalizacja_hurt CASCADE CONSTRAINTS;

DROP TABLE typ_gabinetu_hurt CASCADE CONSTRAINTS;

DROP TABLE typ_oplaty_hurt CASCADE CONSTRAINTS;

DROP TABLE ulica_hurt CASCADE CONSTRAINTS;

DROP TABLE wizyta_hurt CASCADE CONSTRAINTS;

DROP TABLE wojewodztwo_hurt CASCADE CONSTRAINTS;

DROP TABLE wysokosc_zarobkow_hurt CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE gabinet_hurt (
    gabinet_id NUMBER(2) NOT NULL,
    numer      NUMBER(3)
);

ALTER TABLE gabinet_hurt ADD CONSTRAINT gabinet_hurt_pk PRIMARY KEY ( gabinet_id );

CREATE TABLE gabinet_lekarski_hurt (
    gabinet_lekarski_id NUMBER(2) NOT NULL,
    nazwa               VARCHAR2(20)
);

ALTER TABLE gabinet_lekarski_hurt ADD CONSTRAINT gabinet_lekarski_hurt_pk PRIMARY KEY ( gabinet_lekarski_id );

CREATE TABLE miasto_hurt (
    miasto_id NUMBER(2) NOT NULL,
    nazwa     VARCHAR2(20)
);

ALTER TABLE miasto_hurt ADD CONSTRAINT miasto_hurt_pk PRIMARY KEY ( miasto_id );

CREATE TABLE miesiac_hurt (
    miesiac_id INTEGER NOT NULL,
    opis       VARCHAR2(20)
);

ALTER TABLE miesiac_hurt ADD CONSTRAINT miesiac_hurt_pk PRIMARY KEY ( miesiac_id );

CREATE TABLE pacjent_hurt (
    pacjent_id NUMBER(2) NOT NULL,
    nazwisko   VARCHAR2(20),
    imie       VARCHAR2(30)
);

ALTER TABLE pacjent_hurt ADD CONSTRAINT pacjent_hurt_pk PRIMARY KEY ( pacjent_id );

CREATE TABLE panstwo_hurt (
    panstwo_id NUMBER(2) NOT NULL,
    nazwa      VARCHAR2(20)
);

ALTER TABLE panstwo_hurt ADD CONSTRAINT panstwo_hurt_pk PRIMARY KEY ( panstwo_id );

CREATE TABLE pracownik_hurt (
    pracownik_id NUMBER(2) NOT NULL,
    imie         VARCHAR2(20),
    nazwisko     VARCHAR2(30)
);

ALTER TABLE pracownik_hurt ADD CONSTRAINT pracownik_hurt_pk PRIMARY KEY ( pracownik_id );

CREATE TABLE rok_hurt (
    rok_id NUMBER(4) NOT NULL,
    numer  NUMBER(4)
);

ALTER TABLE rok_hurt ADD CONSTRAINT rok_hurt_pk PRIMARY KEY ( rok_id );

CREATE TABLE specjalizacja_hurt (
    specjalizacja_id NUMBER(2) NOT NULL
);

ALTER TABLE specjalizacja_hurt ADD CONSTRAINT specjalizacja_hurt_pk PRIMARY KEY ( specjalizacja_id );

CREATE TABLE typ_gabinetu_hurt (
    typ_gabinetu_id NUMBER(2) NOT NULL,
    opis            VARCHAR2(30)
);

ALTER TABLE typ_gabinetu_hurt ADD CONSTRAINT typ_gabinetu_hurt_pk PRIMARY KEY ( typ_gabinetu_id );

CREATE TABLE typ_oplaty_hurt (
    typ_oplaty_id NUMBER(2) NOT NULL,
    kwota         NUMBER(6, 2)
);

ALTER TABLE typ_oplaty_hurt ADD CONSTRAINT typ_oplaty_hurt_pk PRIMARY KEY ( typ_oplaty_id );

CREATE TABLE ulica_hurt (
    ulica_id NUMBER(2) NOT NULL,
    nazwa    VARCHAR2(20)
);

ALTER TABLE ulica_hurt ADD CONSTRAINT ulica_hurt_pk PRIMARY KEY ( ulica_id );

CREATE TABLE wizyta_hurt (
    wizyta_id            NUMBER(6) NOT NULL,
    pacjent_id           NUMBER(2) NOT NULL,
    gabinet_lekarski_id  NUMBER(2) NOT NULL,
    miesiac_id           INTEGER NOT NULL,
    rok_id               NUMBER(4) NOT NULL,
    typ_oplaty_id        NUMBER(2) NOT NULL,
    gabinet_id           NUMBER(2) NOT NULL,
    pracownik_id         NUMBER(2) NOT NULL,
    specjalizacja_id     NUMBER(2) NOT NULL,
    wysokosc_zarobkow_id NUMBER(2) NOT NULL,
    typ_gabinetu_id      NUMBER(2) NOT NULL,
    ulica_id             NUMBER(2) NOT NULL,
    miasto_id            NUMBER(2) NOT NULL,
    wojewodztwo_id       NUMBER(2) NOT NULL,
    panstwo_id           NUMBER(2) NOT NULL
);

ALTER TABLE wizyta_hurt ADD CONSTRAINT wizyta_hurt_pk PRIMARY KEY ( wizyta_id );

CREATE TABLE wojewodztwo_hurt (
    wojewodztwo_id NUMBER(2) NOT NULL,
    nazwa          VARCHAR2(20)
);

ALTER TABLE wojewodztwo_hurt ADD CONSTRAINT wojewodztwo_hurt_pk PRIMARY KEY ( wojewodztwo_id );

CREATE TABLE wysokosc_zarobkow_hurt (
    wysokosc_zarobkow_id NUMBER(2) NOT NULL,
    kwota                NUMBER(7, 2)
);

ALTER TABLE wysokosc_zarobkow_hurt ADD CONSTRAINT wysokosc_zarobkow_hurt_pk PRIMARY KEY ( wysokosc_zarobkow_id );

ALTER TABLE wizyta_hurt
    ADD CONSTRAINT wizyta_hurt_gabinet_hurt_fk FOREIGN KEY ( gabinet_id )
        REFERENCES gabinet_hurt ( gabinet_id );

ALTER TABLE wizyta_hurt
    ADD CONSTRAINT wizyta_hurt_gabinet_le_hurt_fk FOREIGN KEY ( gabinet_lekarski_id )
        REFERENCES gabinet_lekarski_hurt ( gabinet_lekarski_id );

ALTER TABLE wizyta_hurt
    ADD CONSTRAINT wizyta_hurt_miasto_hurt_fk FOREIGN KEY ( miasto_id )
        REFERENCES miasto_hurt ( miasto_id );

ALTER TABLE wizyta_hurt
    ADD CONSTRAINT wizyta_hurt_miesiac_hurt_fk FOREIGN KEY ( miesiac_id )
        REFERENCES miesiac_hurt ( miesiac_id );

ALTER TABLE wizyta_hurt
    ADD CONSTRAINT wizyta_hurt_pacjent_hurt_fk FOREIGN KEY ( pacjent_id )
        REFERENCES pacjent_hurt ( pacjent_id );

ALTER TABLE wizyta_hurt
    ADD CONSTRAINT wizyta_hurt_panstwo_hurt_fk FOREIGN KEY ( panstwo_id )
        REFERENCES panstwo_hurt ( panstwo_id );

ALTER TABLE wizyta_hurt
    ADD CONSTRAINT wizyta_hurt_pracownik_hurt_fk FOREIGN KEY ( pracownik_id )
        REFERENCES pracownik_hurt ( pracownik_id );

ALTER TABLE wizyta_hurt
    ADD CONSTRAINT wizyta_hurt_rok_hurt_fk FOREIGN KEY ( rok_id )
        REFERENCES rok_hurt ( rok_id );

ALTER TABLE wizyta_hurt
    ADD CONSTRAINT wizyta_hurt_spec_hurt_fk FOREIGN KEY ( specjalizacja_id )
        REFERENCES specjalizacja_hurt ( specjalizacja_id );

ALTER TABLE wizyta_hurt
    ADD CONSTRAINT wizyta_hurt_typ_gab_hurt_fk FOREIGN KEY ( typ_gabinetu_id )
        REFERENCES typ_gabinetu_hurt ( typ_gabinetu_id );

ALTER TABLE wizyta_hurt
    ADD CONSTRAINT wizyta_hurt_typ_oplaty_hurt_fk FOREIGN KEY ( typ_oplaty_id )
        REFERENCES typ_oplaty_hurt ( typ_oplaty_id );

ALTER TABLE wizyta_hurt
    ADD CONSTRAINT wizyta_hurt_ulica_hurt_fk FOREIGN KEY ( ulica_id )
        REFERENCES ulica_hurt ( ulica_id );

ALTER TABLE wizyta_hurt
    ADD CONSTRAINT wizyta_hurt_woje_hurt_fk FOREIGN KEY ( wojewodztwo_id )
        REFERENCES wojewodztwo_hurt ( wojewodztwo_id );

ALTER TABLE wizyta_hurt
    ADD CONSTRAINT wizyta_hurt_wysokosc_z_hurt_fk FOREIGN KEY ( wysokosc_zarobkow_id )
        REFERENCES wysokosc_zarobkow_hurt ( wysokosc_zarobkow_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             0
-- ALTER TABLE                             29
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
